### PR TITLE
Update cloudhub-fabric.adoc

### PR DESCRIPTION
**Pull request by atheedom**
Change the CH implementation of OSv2 to DynamoDB, as implied it is here https://github.com/mulesoft/object-store/blob/develop/ARCHITECTURE.md

### CODE REVIEW

**Review by valkyrie69 — COMMENTED** [review]
Amazon SQS is still used for worker scaling and VM queue load balancing? So the only implementation change is that now object stores are stored using DynamoDB?

Just want to verify that's correct.

**Comment by nishantkakar** [comment]
I don't see how SQS is used for Worker Scaling. Also, Cloudhub ObjectStore is currently using MySQL to store objects in the ObjectStore not DynamoDB or SQS.

**Comment by nishantkakar** [comment]
We have a plan to phase out OSv1 and move to OSv2 which uses DynamoDB. @steveCluster might be able to provide more information regarding OSv2

**Comment by steveCluster** [comment]
Here are the docs for OSv2: https://docs.mulesoft.com/object-store/

We do use dynamodb and S3 in the backend, but we don't really advertise that to customers.

**Comment by valkyrie69** [comment]
@steveCluster  I think the first sentence should be removed entirely. 
Then:

Object stores in your applications are also always stored persistently, even if you did not enable persistent queues for your application.

**Comment by steveCluster** [comment]
George Hoffer is the docs guy from our team.  You should coordinate any changes with him.

Object stores are not always stored persistently.  It's a long conversation that I can go over with you in person.

**Comment by valkyrie69** [comment]
@steveCluster  This is actually in my doc--not George's. It's not about the object store, it's in the context of CloudHub, and I'm fairly sure that in that context object stores in the app are stored persistently. I'll verify with the CH team. Thanks!

**Comment by valkyrie69** [comment]
Not going to make update. Don't need to doc underlying technology and implementation.

**Pull request closed without merging**
