### PR TITLE
W-11411331-clarify-Renew-Cert-nonGUI

### PR DESCRIPTION
**Pull request by luanamulesoft**
# Writer's Quality Checklist

Before merging your PR, did you:

- [x] Run spell checker
- [x] Run link checker to check for broken xrefs
- [x] Check for orphan files
- [x] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [x] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

### CODE REVIEW

**Comment by yunmei-zhang** [comment]
Hi @luanamulesoft, the title "Renew a Certificate after it expires" seems to be not accurate. 
Could you please consider revising it to something like "An alternative method for renewing a certificate" as the steps under the existing "Renew a Certificate after it expires" are not technically only for "Ater it expires". The steps can be followed by the customer who prefers to renew via the command line or when the update certificate failed in GUI.

**Review by pqxmulesoft — DISMISSED** [review]
LGTM

**Comment by luanamulesoft** [comment]
> 

Hi @yunmei-zhang. I changed the title of the command line instructions as suggested.

**Comment by yunmei-zhang** [comment]
LGTM

**Review by tasmoore — APPROVED** [review]

**Pull request merged**
