### PR TITLE
Update vpn-about.adoc

### PR DESCRIPTION
**Pull request by dtufino**
mentioned PFS requirement as per AWS guidelines

### CODE REVIEW

**Review by danieldiaz-mule — CHANGES_REQUESTED** [review]
This is redundant, having a diffie-hellman group in phase 2 implies that PFS is enabled (the group is only required with PFS on).
https://community.cisco.com/t5/vpn/dh-group-in-phase-1-and-phase-2/td-p/2017903

If we want to clarify that PFS is a requirement, we should do it explicitly in the requirements section for each connection type.

**Comment by hannanelson** [comment]
So @danieldiaz-mule, it sounds like this PR is unnecessary and I should close?

**Comment by danieldiaz-mule** [comment]
> So @danieldiaz-mule, it sounds like this PR is unnecessary and I should close?

To me, yes... @dtufino do you have any specific context as to why we need this?

**Comment by dtufino** [comment]
@danieldiaz-mule  For some customers it may not be apparent that PFS is a requirement so we should probably clarify as it is stated in AWS documentation. I agree it should be added in the requirement section instead.

**Comment by hannanelson** [comment]
Closing per Daniel

**Pull request closed without merging**
